import { TailwindScreenSizeIndicator } from "@/components/dev/tw-screensize-indicator";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import type { Metadata } from "next";
import { Bricolage_Grotesque, Figtree } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const bricolage_grotesque = Bricolage_Grotesque({
  subsets: ["vietnamese"],
  variable: "--font-bricolage-grotesque",
});

const titoli = localFont({
  src: "../public/titoliDiTesta.woff2",
  variable: "--font-titoli",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${figtree.variable} ${titoli.variable} ${bricolage_grotesque.variable}`}
    >
      <body className={`antialiased`}>
        <div className="relative mx-auto flex min-h-screen flex-col scroll-smooth">
          <Header />
          <main className="flex flex-1 flex-col">{children}</main>
          <Footer />
        </div>
        <TailwindScreenSizeIndicator />
      </body>
    </html>
  );
}
