import { MenuItem } from "@/_types";

export const banh_mi: MenuItem[] = [
  {
    id: "beef_banh_mi",
    category: "banh_mi",
    title: "Bánh Mì Bò Xào Tỏi",
    subtitle: "Sauteéd Beef Bánh Mì",
    description: "Served with tater tots",
    price: 13,
    imgSrc: "/menu/banh-mi/beef_banh_mi.png",
    dietary: ["gluten", "beef"],
    badge: "best_seller",
  },
  {
    id: "fish_banh_mi",
    category: "banh_mi",
    title: "Bánh Mì Cá Chiên Giòn",
    subtitle: "Battered Fish Bánh Mì",
    description: "Served with tater tots",
    price: 13,
    imgSrc: "/menu/banh-mi/fish_banh_mi.png",
    dietary: ["gluten", "seafood"],
    badge: "best_seller",
  },
  {
    id: "ham_banh_mi",
    category: "banh_mi",
    title: "Bánh Mì Việt Ham Truyền Thống",
    subtitle: "Traditional Ham Bánh Mì",
    price: 11,
    imgSrc: "/menu/banh-mi/ham_banh_mi.png",
    dietary: ["gluten", "pork"],
    badge: "best_seller",
  },
  {
    id: "banh_mi_ga_xa",
    category: "banh_mi",
    title: "Bánh Mì Gà Nướng Xả",
    subtitle: "Lemongrass Chicken Bánh Mì",
    price: 12,
    imgSrc: "/menu/banh-mi/banh_mi_ga_xa.png",
    dietary: ["gluten", "chicken"],
  },
  {
    id: "banh_mi_ga_mat_ong",
    category: "banh_mi",
    title: "Bánh Mì Gà Nướng Tỏi Mật Ong",
    subtitle: "Honey Garlic Chicken Bánh Mì",
    price: 12,
    imgSrc: "/menu/banh-mi/banh_mi_ga_mat_ong.png",
    dietary: ["gluten", "chicken"],
    badge: "best_seller",
  },
  {
    id: "tofu_banh_mi",
    category: "banh_mi",
    title: "Bánh Mì Đậu Phụ Chiên Uớp Xả",
    subtitle: "Lemongrass Tofu Bánh Mì",
    price: 11,
    imgSrc: "/menu/banh-mi/tofu_banh_mi.png",
    dietary: ["gluten", "vegetarian"],
  },
  {
    id: "avocado_banh_mi",
    category: "banh_mi",
    title: "Bánh Mì Bơ",
    subtitle: "Avocado Bánh Mì",
    price: 11,
    imgSrc: "/menu/banh-mi/avocado_banh_mi.png",
    dietary: ["gluten", "vegetarian"],
  },
];
