import { MenuItem } from "@/_types";

export const drinks: MenuItem[] = [
  {
    id: "coco_kumquat",
    category: "drink",
    title: "Dừa Tắc Hạt Chia",
    subtitle: "Coconut Kumquat",
    description: "Coconut water, kumquat, chia seeds",
    price: 7,
    imgSrc: "/menu/drink/coco-kumquat.png",
    badge: "new",
  },
  {
    id: "kumquat_tea",
    category: "drink",
    title: "Trà Tắc Hạt Chia",
    subtitle: "Kumquat Chia Tea",
    description: "Thai green tea with kumquat and chia seeds",
    price: 7,
    imgSrc: "/menu/drink/kumquat-tea.png",
    badge: "new",
  },
  {
    id: "tra_dao",
    category: "drink",
    title: "Trà Đào",
    subtitle: "Peachy Iced Tea",
    description: "Featuring Phúc Long Tea",
    price: 7,
    imgSrc: "/menu/drink/tra-dao.png",
    badge: "best_seller",
  },
  {
    id: "soda_chanh",
    category: "drink",
    title: "Soda Chanh",
    subtitle: "Sparkly Soda",
    description:
      "Mixed with lime, mint, and choice of up to 2 flavours: citron, coconut, hibiscus, lychee, mango, peach, strawberry",
    price: 6.5,
    imgSrc: "/menu/drink/soda-chanh.png",
    badge: "best_seller",
  },
  {
    id: "smoothie",
    category: "drink",
    title: "Sinh Tố",
    subtitle: "Smoothie",
    description:
      "Blended with condensed milk, and choice of up to 2 fruits: avocado, blueberry, mango, strawberry",
    price: 7,
    imgSrc: "/menu/drink/smoothie.png",
    dietary: ["dairy"],
  },
  {
    id: "coconut_coffee_slush",
    category: "drink",
    title: "Cà Phê Cốt Dừa Đá Xay",
    subtitle: "Coconut Coffee Slush",
    description: "Blended with Vietnamese coffee, condensed milk, coconut milk",
    price: 7.5,
    imgSrc: "/menu/drink/coconut-coffee-slush.png",
    badge: "best_seller",
    dietary: ["dairy"],
  },
  {
    id: "ca_phe_muoi",
    category: "drink",
    title: "Cà Phê Muối",
    subtitle: "Salted Foam Vietnamese Coffee",
    description: "Vietnamese coffee, condensed milk, salted foam topped with cocoa powder",
    price: 7.5,
    imgSrc: "/menu/drink/ca-phe-muoi.png",
    badge: "best_seller",
    dietary: ["dairy"],
  },
  {
    id: "ca_phe",
    category: "drink",
    title: "Cà Phê",
    subtitle: "Vietnamese Drip Coffee",
    description:
      "Vietnamese phin filter drip coffee\nChoice: hot | iced, with | without condensed milk",
    price: 6.5,
    imgSrc: "/menu/drink/ca-phe.png",
    dietary: ["dairy"],
  },
  {
    id: "jasmine_tea",
    category: "drink",
    title: "Trà Hoa Nhài",
    subtitle: "Jasmine Tea",
    description: "Unlimited refills",
    price: 1,
    imgSrc: "/menu/drink/jasmine-tea.png",
  },
  {
    id: "soft_drink",
    category: "drink",
    title: "Nước Ngọt",
    subtitle: "Soft Drink",
    description: "Coke, Sprite",
    price: 3,
  },
];
